title:            Xiaoxiao blog
description:      Describe your website here.
disqus_shortname: shortname
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://xiaoxiaozhao.net

# Owner/author information
owner:
  name:           Xiaoxiao Zhao
  avatar:         avatar.jpg
  bio:            "I am Xiaoxiao. IS student, web developer. Big big fan of cats. Love cooking and traveling. Buddhist "
  email:          zxxaki@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: zhaomimimi       
  facebook:       
  github: zhaomizhi         
  stackexchange:  
  linkedin:       
  instagram: zhao_mi     
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5